### ISSUE TITLE
to_gbq() fails with columns having bools and NaNs

### ISSUE THREAD

**Issue by vlegout** [googleapis/python-bigquery-pandas#488]
Hi,

I've got an issue running `to_gbq()` with a DataFrame that has a column containing bools and NaNs. It can be reproduced with the example below.

From what I understand, the dtype for this column is `object`, thus `pandas-gbq` detects this column as `string` and `pyarrow` is not happy because it contains `bool` entries. I'm not sure what's the best way to fix this, would you have any idea ? I'd be happy to write a patch if you have some pointers on how to fix.

#### Environment details

  - OS type and version: Linux
  - Python version: 3.9.9
  - pip version: 20.3.4
  - `pandas-gbq` version: 0.17.1

#### Steps to reproduce

Can be reproduced using the following snippet.

#### Code example

```python
#!/usr/bin/python3

import pandas_gbq

import pandas as pd
import numpy as np

dtf = pd.DataFrame({'col': [np.NaN, False, True]})

pandas_gbq.to_gbq(dtf, 'dataset.table')
```

#### Stack trace
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    pandas_gbq.to_gbq(dtf, 'dataset.table')
  File "venv/lib/python3.9/site-packages/pandas_gbq/gbq.py", line 1148, in to_gbq
    connector.load_data(
  File "venv/lib/python3.9/site-packages/pandas_gbq/gbq.py", line 565, in load_data
    chunks = load.load_chunks(
  File "venv/lib/python3.9/site-packages/pandas_gbq/load.py", line 237, in load_chunks
    load_parquet(
  File "venv/lib/python3.9/site-packages/pandas_gbq/load.py", line 129, in load_parquet
    client.load_table_from_dataframe(
  File "venv/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2649, in load_table_from_dataframe
    _pandas_helpers.dataframe_to_parquet(
  File "venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 589, in dataframe_to_parquet
    arrow_table = dataframe_to_arrow(dataframe, bq_schema)
  File "venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 532, in dataframe_to_arrow
    bq_to_arrow_array(get_column_or_index(dataframe, bq_field.name), bq_field)
  File "venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 293, in bq_to_arrow_array
    return pyarrow.Array.from_pandas(series, type=arrow_type)
  File "pyarrow/array.pxi", line 913, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 311, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Expected bytes, got a 'bool' object
```

Thanks!
Vincent

**Comment by tswast** [comment]
Thanks so much for the report and reproducible test case! I'll look into this. I suspect we've got a problem in our type inference.

**Comment by tswast** [comment]
In [9]: import pandas_gbq
   ...: 
   ...: import pandas as pd
   ...: import numpy as np
   ...: 
   ...: dtf = pd.DataFrame({'col': [np.NaN, False, True]})
   ...: 

In [10]: dtf.dtypes
Out[10]: 
col    object
dtype: object

In [11]: pandas_gbq.to_gbq(dtf, 'swast-scratch.my_dataset.issue488', if_exists="replace", table_schema=[{"name": "col",
    ...: "type": "BOOLEAN"}])
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14926.35it/s]
```

I hope that these workarounds are sufficient to solve your problem.

**Comment by vlegout** [comment]
Thanks for looking into this, I agree with your rationale to close the issue.

I'll look at the workarounds you proposed, thanks!
