### ISSUE TITLE
NUMERIC Field failing with conversion from NoneType to Decimal is not supported

### ISSUE THREAD

**Issue by ismailsimsek** [googleapis/python-bigquery-pandas#584]
Saving data to NUMERIC Field failing with conversion from NoneType to Decimal is not supported

- python 3.9
- pandas 1.5.1

#### Stack trace
```

...........

df.to_gbq(project_id=self.client.project,
          File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas-1.5.1-py3.9-macosx-10.9-x86_64.egg/pandas/core/frame.py", line 2168, in to_gbq
gbq.to_gbq(
    File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas-1.5.1-py3.9-macosx-10.9-x86_64.egg/pandas/io/gbq.py", line 218, in to_gbq
pandas_gbq.to_gbq(
    File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas_gbq-0.17.9-py3.9.egg/pandas_gbq/gbq.py", line 1198, in to_gbq
connector.load_data(
    File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas_gbq-0.17.9-py3.9.egg/pandas_gbq/gbq.py", line 591, in load_data
chunks = load.load_chunks(
    File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas_gbq-0.17.9-py3.9.egg/pandas_gbq/load.py", line 240, in load_chunks
load_parquet(
    File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas_gbq-0.17.9-py3.9.egg/pandas_gbq/load.py", line 128, in load_parquet
dataframe = cast_dataframe_for_parquet(dataframe, schema)
File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas_gbq-0.17.9-py3.9.egg/pandas_gbq/load.py", line 103, in cast_dataframe_for_parquet
cast_column = dataframe[column_name].map(decimal.Decimal)
File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas-1.5.1-py3.9-macosx-10.9-x86_64.egg/pandas/core/series.py", line 4539, in map
new_values = self._map_values(arg, na_action=na_action)
File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas-1.5.1-py3.9-macosx-10.9-x86_64.egg/pandas/core/base.py", line 890, in _map_values
new_values = map_f(values, mapper)
File "pandas/_libs/lib.pyx", line 2918, in pandas._libs.lib.map_infer
TypeError: conversion from NoneType to Decimal is not supported
```

**Comment by ismailsimsek** [comment]
Chaging dataframe field type to `.astype('float64')` works but then it fails with following error 

is there any parameter to allow casting? or avid this error ? 

```
Traceback (most recent call last):
File "/Users/xxxx/.local/lib/python3.9/site-packages/pandas_gbq-0.17.9-py3.9.egg/pandas_gbq/load.py", line 131, in load_parquet
client.load_table_from_dataframe(
    File "/Users/xxxx/.local/lib/python3.9/site-packages/google_cloud_bigquery-3.3.5-py3.9.egg/google/cloud/bigquery/client.py", line 2628, in load_table_from_dataframe
_pandas_helpers.dataframe_to_parquet(
    File "/Users/xxxx/.local/lib/python3.9/site-packages/google_cloud_bigquery-3.3.5-py3.9.egg/google/cloud/bigquery/_pandas_helpers.py", line 672, in dataframe_to_parquet
arrow_table = dataframe_to_arrow(dataframe, bq_schema)
File "/Users/xxxx/.local/lib/python3.9/site-packages/google_cloud_bigquery-3.3.5-py3.9.egg/google/cloud/bigquery/_pandas_helpers.py", line 617, in dataframe_to_arrow
bq_to_arrow_array(get_column_or_index(dataframe, bq_field.name), bq_field)
File "/Users/xxxx/.local/lib/python3.9/site-packages/google_cloud_bigquery-3.3.5-py3.9.egg/google/cloud/bigquery/_pandas_helpers.py", line 342, in bq_to_arrow_array
return pyarrow.Array.from_pandas(series, type=arrow_type)
File "pyarrow/array.pxi", line 1033, in pyarrow.lib.Array.from_pandas
File "pyarrow/array.pxi", line 312, in pyarrow.lib.array
File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Rescaling Decimal256 value would cause data loss
```

**Comment by chalmerlowe** [comment]
Based on my understanding of these issues, this does not appear to be an issue with how the `python-bigquery` connector library is handling the data. It appears to be an issue with how the dependencies (`pyarrow` or `pandas`) are handling data conversion.

Going to close this as `will not fix`.
